name: Deploy to Nginx

on:
  push:
    branches:
      - main # 替换成你的主分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: |
        npm run build

    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: ./dist
        REMOTE_HOST: 43.134.23.181
        REMOTE_USER: ubuntu
        TARGET: /home/ubuntu

    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: ./dist
        REMOTE_HOST: 43.134.23.181
        REMOTE_USER: ubuntu
        TARGET: /var/www/html